
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route for /api/patients/** to patient-service
        - id: patient-service-route
          uri: http://patient-service:9999
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: auth-service-route
          uri: http://auth-service:2005
          predicates:
            - Path=/auth/**


        - id: api-docs-patient-route
          uri: http://patient-service:9999
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs

        - id: swagger-ui-patient-route
          uri: http://patient-service:9999
          predicates:
            - Path=/swagger-ui/**
          filters:
            - RewritePath=/swagger-ui/(?<segment>.*), /swagger-ui/${segment}

        - id: api-docs-auth-route
          uri: http://auth-service:4005
          predicates:
            - Path=/swagger-ui/**
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs

server:
  port: 2004
