### GET request to example server
PUT http://localhost:9999/patients/update/123e4567-e89b-12d3-a456-426614174013
Content-Type: application/json

{
  "name": "Jane Doe Doe",
  "email": "daniel@example.com",
  "phone": "0712345678",
  "address": "456 Elm Street, Nairobi",
  "gender": "Female",
  "bloodGroup": "A+",
  "dob": "1990-05-20",
  "admissionDate": "",
  "status": "admitted"
}

###