spring:
  application:
    name: Patient-Service
#  datasource:
#    url: jdbc:h2:mem:testdb   # In-memory H2 database
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: sa
#  h2:
#    console:
#      enabled: true            # Enables H2 web console
#      path: /h2-console        # Console URL path
#  jpa:
#    hibernate:
#      ddl-auto: update         # Or 'create', 'validate', 'none', etc.
#    show-sql: true             # Logs SQL queries
#    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 9999

logging:
  level:
    root: info
